### ISSUE TITLE
White text with white background in programming language dropdown

### ISSUE THREAD

**Issue by tomchen** [ast-grep/ast-grep-vscode#443]
White text with white bg here.

(bg color is system defined and varies on different platform?)

![Image](https://github.com/user-attachments/assets/38dc219b-f7b0-438c-aef7-e62f8af10de6)

**Comment by HerringtonDarkholme** [comment]
@tomchen what's your system theme? can you also check it with https://ast-grep.github.io/playground.html?

**Comment by tomchen** [comment]
@HerringtonDarkholme My system theme is light (default). In the playground:

- The language dropdown is always black text + white bg in light and dark theme, which is OK
- The Strictness dropdown is black text + white bg in light mode, and light grey text + white bg in dark mode, making it a little unreadable in dark mode
- Other elements all look normal

![Image](https://github.com/user-attachments/assets/9012a2e3-48f7-4acc-86e6-115d76a0cfb5)

**Comment by HerringtonDarkholme** [comment]
@tomchen can you try change the select element's color to red or black? i believe this is windows specific behavior where the select element inherit the color

**Comment by tomchen** [comment]
In the playground, I changed that `<select>`'s css color to red, then the selected text (I mean the first line, or the selected value that is in select but outside `<option>`) as well as all `<option>` text, become red. `<option>`'s style can be set to overwrite `<select>`'s.

I'm not sure what you want to know. I didn't have a careful look at your css and test on other platform, but I guess: in windows, for the UA default style, `<option>` bg is always white no matter light or dark system theme, and this behavior is different than other platform? So just set option's bg to black in dark mode to solve the problem?

**Comment by tomchen** [comment]
> [@HerringtonDarkholme](https://github.com/HerringtonDarkholme) My system theme is light (default). [...]

Oh not sure if this info helps: here although my system theme is light, VS Code seems to default to dark modern theme which I just checked I'm using (well you can clearly see on the first screenshot that my VS Code is dark not light)

**Comment by HerringtonDarkholme** [comment]
@tomchen can you do me a favor and try adding `color: unset;` to select option? thanks

I think it should fix both vscode and playground on windows

**Comment by tomchen** [comment]
Not working

![Image](https://github.com/user-attachments/assets/32f05f72-fb5b-4297-99b5-ef3a5c8ec906)

**Comment by HerringtonDarkholme** [comment]
@tomchen i pushed a fix. would you like to verify it?

**Comment by tomchen** [comment]
Strictness OK

![Image](https://github.com/user-attachments/assets/81858f17-c15e-45c7-8020-1e08191741ea) ![Image](https://github.com/user-attachments/assets/a9977fed-e684-496f-a790-5b826f0b0bca)

But Language

![Image](https://github.com/user-attachments/assets/c7da9162-88db-498f-bf70-60e61ea9e17f)

text color should be white in dark mode

![Image](https://github.com/user-attachments/assets/025f3432-a208-4447-906f-792358559fde)

the first "JavaScript" shouldn't have white bg instead of transparent bg in light mode

**Comment by HerringtonDarkholme** [comment]
@tomchen i pushed a new change, would you like to try that?

**Comment by tomchen** [comment]
@HerringtonDarkholme 

Just tried

You fixed this:

> ![Image](https://github.com/user-attachments/assets/025f3432-a208-4447-906f-792358559fde)
> 
> the first "JavaScript" shouldn't have white bg instead of transparent bg in light mode

But this problem still persists:

> ![Image](https://github.com/user-attachments/assets/c7da9162-88db-498f-bf70-60e61ea9e17f)
> 
> text color should be white in dark mode

**Comment by HerringtonDarkholme** [comment]
@tomchen can you try something like change the option color CSS to `color: white !important` ?

**Comment by tomchen** [comment]
no need for !important, just set color: white on a specific option element will fix that

![Image](https://github.com/user-attachments/assets/25c0fca8-b31f-4ab1-ad7f-5ad8c2f40068)

So when you add `color: white`, these `color: white` needs to be overwritten
```css
.selector-option-text[data-v-ef45881a] {
    color: var(--vp-custom-selector-option-text);
}
option {
    background-color: var(--vp-c-bg);
    color: var(--vp-c-text-1);
}
```
Or remove `.selector-option-text[data-v-ef45881a]` and use global option's `color: var(--vp-c-text-1);` in dark mode

<details>
  <summary>CSS precedence order in case you need it</summary>
CSS specificity and precedence determine which styles apply when multiple rules target the same element. Here's how different selectors compare in order of precedence (from lowest to highest specificity):

1 `option` → (0,0,1)

Targets all `<option>` elements.

2 `.class` → (0,1,0)

Targets elements with a specific class.

3 `option.class` → (0,1,1)

Targets `<option>` elements with a specific class.

4 `.class[data]` → (0,2,0)

Targets elements with a class and a specific attribute.

5 `select.class-sel option.class` → (0,2,1)

Targets `<option>` elements within a `<select>` that has a specific class.

6 `#id` → (1,0,0)

IDs have higher specificity than classes.

7 `!important` → Overrides everything (except other !important rules with higher specificity).

General Precedence Rules:

The more specific selector wins.

If two selectors have the same specificity, the last defined rule in the stylesheet wins.

Inline styles (style="color: red") have higher specificity than any CSS rule ((1,0,0,0)).

!important overrides specificity but can be beaten by another !important rule with higher specificity.
</details>

**Comment by HerringtonDarkholme** [comment]
Playground should be fixed. Lang dropdown fix should be shipped next release

**Comment by tomchen** [comment]
@HerringtonDarkholme you mean lang dropdown fix _in VS Code extension_ should be shipped next release?

or lang dropdown fix _in Playground_ should be shipped next release?

Because currently this problem still persists in Playground:

> ![Image](https://github.com/user-attachments/assets/c7da9162-88db-498f-bf70-60e61ea9e17f)
> text color should be white in dark mode

**Comment by HerringtonDarkholme** [comment]
@tomchen i have already added it in option. can you help fix it? i don't have windows machine

<img width="367" alt="Image" src="https://github.com/user-attachments/assets/0c4aadce-9cd9-422a-b046-1ef9bf29355c" />

**Comment by tomchen** [comment]
@HerringtonDarkholme Oh it's OK now. Thanks.

At the time of my previous post and attempt, the new asset files might not have been fully deployed on github page (I tried ctrl+F5 hard refresh and even another clean browser but still had the issue)
